plugins:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Metrics/MethodLength:
  Exclude:
    - 'test/test_scalar.rb'
    - 'test/scalar/**/*'

Style/Documentation:
  Enabled: false
